# Generated by Django 3.1.7 on 2021-05-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
