const authActions = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS', 
    SIGNUP_FAIL: 'SIGNUP_FAIL', 
    ACTIVATION_SUCCESS: 'ACTIVATION_SUCCESS',
    ACTIVATION_FAIL: 'ACTIVATION_FAIL',
    AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
    AUTHENTICATION_FAIL: 'AUTHENTICATION_FAIL',
    USER_LOAD_SUCCESS: 'USER_LOAD_SUCCESS',
    USER_LOAD_FAIL: 'USER_LOAD_FAIL',
    PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    GOOGLE_AUTH_SUCCESS: 'GOOGLE_AUTH_SUCCESS',
    GOOGLE_AUTH_FAIL: 'GOOGLE_AUTH_FAIL',
    FACEBOOK_AUTH_SUCCESS: 'FACEBOOK_AUTH_SUCCESS',
    FACEBOOK_AUTH_FAIL: 'FACEBOOK_AUTH_FAIL',
}

const ActionTypes = {
    authActions: authActions
};

export default ActionTypes;