# Generated by Django 3.1.7 on 2021-05-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
